add support for params in memory execution and stablize load_3
ropnop/go-clr pull request #1
Opened 2020-08-02 10:12 UTC by ayoul3

Hello,
Loved your blog post! I was looking for a CLR loading implem in Go. Yours spared many nights of working with COM objects :) I thank you for that !
I added support for parameters when executing in memory since you mentioned it in the blog post. I was also having trouble with load_3, I think because the GC was messing with the dereferenced pointers. Anyway I proposed a fix that makes it much more stable.
This PR is just an FYI, please see to adapt the code to your style ;)

Cheers,

2020-08-04 16:10 UTC, ropnop commented on examples/CLRWrapper/CLRWrapper.go
> +	exebytes, err := ioutil.ReadFile(`hellworld.exe`)
Can you fix this typo to `helloworld.exe`? Then it will work with my existing test exe 😄

2020-08-04 16:13 UTC, ropnop requested changes

2020-08-04 16:13 UTC, ropnop commented on go-clr.go
> +func ExecuteByteArray(rawBytes []byte, params []string) (retCode int32, err error) {
Do you mind updating the docstring to reflect the new argument?

2020-08-04 16:13 UTC, ropnop commented on go-clr.go
> +func PrepareParameters(params []string) (uintptr, error) {
Can you add a docstring for the exported functions?

2020-08-04 16:13 UTC, ropnop commented on methodinfo.go
> +func (obj *MethodInfo) GetString(addr *uintptr) error {
docstring for exported functions

2020-08-04 16:13 UTC, ropnop commented on safearray.go
> +func CreateEmptySafeArray(arrayType int, size int) (unsafe.Pointer, error) {
docstring for exported functions

2020-08-04 16:13 UTC, ropnop commented on safearray.go
> +func SysAllocString(str string) (unsafe.Pointer, error) {
docstring for exported functions

2020-08-04 16:13 UTC, ropnop commented on safearray.go
> +func SafeArrayPutElement(array, btsr unsafe.Pointer, index int) (err error) {
docstring for exported functions

2020-08-04 16:15 UTC, ropnop commented
This is AMAZING work!! Thank you so much. I fought that GC issue with safearray for so long - this is so much better. I've been testing and it all looks good and works great - do you mind just adding some docs to the exported functions? THANK YOU!

2020-08-04 22:37 UTC, ayoul3 commented
You're very much welcome mate! I am barely building on the great foundation you laid out! Unless my sleepy eyes are betraying me, I believe I applied all of your comments!
Cheers ;)

2020-08-05 15:20 UTC, ropnop approved these changes

2020-08-05 15:21 UTC, merged

2020-08-05 15:21 UTC, ropnop commented
Looks great! Thanks again 👍